name: Deploy to Smithery

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Deploy to Smithery
        run: |
          # Add Smithery deployment command here
          # This will be provided by Smithery.ai
        env:
          SMITHERY_API_KEY: ${{e14e2f82-4d2c-44ac-8f47-cd41a89fdbdd}}
